// ESM serverless function for Vercel
// Sends a structured email to site admins and a confirmation copy to the client
/* eslint-env node */
import { Resend } from 'resend';

// Production-configurable emails
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'info@citrixconsulting.co.uk';
// Use Resend's default sender domain so you DON'T need any domain/DNS setup
const FROM_EMAIL = process.env.FROM_EMAIL || 'Citrix Consulting <onboarding@resend.dev>';

function buildAdminHtml(payload) {
  const { name, email, company, phone, service, message } = payload;
  const safe = (v) => (typeof v === 'string' ? v.replace(/</g, '&lt;').replace(/>/g, '&gt;') : '');
  return `
  <div style="font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu, Cantarell, Noto Sans, Helvetica Neue, Arial; color:#0f172a;">
    <h2 style="margin:0 0 12px;">New Contact Form Submission</h2>
    <p style="margin:0 0 16px; color:#334155;">You have received a new enquiry from the website.</p>
    <table style="width:100%; border-collapse:collapse;">
      <tbody>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc; width:180px;">Name</td>
          <td style="padding:8px 12px;">${safe(name)}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc;">Email</td>
          <td style="padding:8px 12px;">${safe(email)}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc;">Company</td>
          <td style="padding:8px 12px;">${safe(company)}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc;">Phone</td>
          <td style="padding:8px 12px;">${safe(phone)}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc;">Service of Interest</td>
          <td style="padding:8px 12px;">${safe(service)}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px; background:#f8fafc; vertical-align:top;">Message</td>
          <td style="padding:8px 12px; white-space:pre-wrap;">${safe(message)}</td>
        </tr>
      </tbody>
    </table>
    <p style="margin-top:16px; color:#334155;">This email was generated by the website contact form.</p>
  </div>`;
}

function buildClientHtml(payload) {
  const { name, message } = payload;
  const safe = (v) => (typeof v === 'string' ? v.replace(/</g, '&lt;').replace(/>/g, '&gt;') : '');
  return `
  <div style="font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu, Cantarell, Noto Sans, Helvetica Neue, Arial; color:#0f172a;">
    <h2 style="margin:0 0 12px;">Thanks, we received your message</h2>
    <p style="margin:0 0 12px; color:#334155;">Hi ${safe(name) || 'there'},</p>
    <p style="margin:0 0 16px; color:#334155;">Thanks for contacting Citrix Consulting. A member of our team will get back to you within 24 hours.</p>
    <div style="border:1px solid #e2e8f0; border-radius:8px; padding:12px; background:#f8fafc;">
      <div style="font-weight:600; margin-bottom:8px;">Your message:</div>
      <div style="white-space:pre-wrap;">${safe(message)}</div>
    </div>
    <p style="margin-top:16px; color:#334155;">If you did not submit this request, please ignore this email.</p>
  </div>`;
}

export default async function handler(request, response) {
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.RESEND_API_KEY;

  let body;
  try {
    body = request.body && typeof request.body === 'object' ? request.body : await parseJson(request);
  } catch (err) {
    return response.status(400).json({ error: 'Invalid JSON body' });
  }

  const { name, email, company, phone, service, message, consent } = body ?? {};

  if (!name || !email || !message) {
    return response.status(400).json({ error: 'Missing required fields: name, email, message' });
  }

  // Optionally enforce consent if the checkbox is present
  if (typeof consent === 'boolean' && consent !== true) {
    return response.status(400).json({ error: 'Consent is required' });
  }

  try {
    if (!apiKey) {
      // Dev fallback: simulate success without sending real emails
      console.warn('RESEND_API_KEY missing — simulating email send (dev mode).');
      console.info('Simulated admin email to:', ADMIN_EMAIL, '\nPayload:', { name, email, company, phone, service });
      console.info('Simulated client email to:', email);
      return response.status(200).json({ ok: true, simulated: true });
    }

    const resend = new Resend(apiKey);

    // Send to admin
    await resend.emails.send({
      from: FROM_EMAIL,
      to: [ADMIN_EMAIL],
      subject: `[Website] New contact from ${name}`,
      reply_to: email,
      html: buildAdminHtml({ name, email, company, phone, service, message }),
    });

    // Send confirmation to client
    await resend.emails.send({
      from: FROM_EMAIL,
      to: [email],
      subject: 'We received your message — Citrix Consulting',
      html: buildClientHtml({ name, message }),
    });

    return response.status(200).json({ ok: true });
  } catch (error) {
    console.error('Email send error', error);
    return response.status(500).json({ error: 'Failed to send email' });
  }
}

async function parseJson(req) {
  const buffers = [];
  for await (const chunk of req) {
    buffers.push(chunk);
  }
  const str = Buffer.concat(buffers).toString('utf8');
  return JSON.parse(str);
}


